name: stopwatch
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  path: ^1.8.2
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  connectivity_plus: ^3.0.3
  firebase_remote_config: ^3.0.15
  device_info_plus: ^8.1.0
  firebase_core: ^2.8.0
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
